config/routes.rb
Rails.application.routes.draw do

  devise_for :accounts
  root to: 'pages#home'

  get 'about',    to: 'pages#about', as: :about
  get 'contacts', to: 'pages#contacts', as: :contacts

  resources :jqueries

end

app/models/account.rb
class Account < ApplicationRecord

  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  mount_uploader :avatar, AvatarUploader

  def full_name
    "#{first_name} #{last_name}"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/jquery.rb
class Jquery < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name, :last_name, :avatar, :avatar_cache])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name, :avatar, :avatar_cache])
  end

end

app/controllers/jqueries_controller.rb
class JqueriesController < ApplicationController

  before_action :set_jquery, only: %i[ show edit update destroy ]

  def index
    @jqueries = Jquery.all
  end

  def show; end
  def edit; end

  def new
    @jquery = Jquery.new
  end

  def create
    @jquery = Jquery.new(jquery_params)

    respond_to do |format|
      if @jquery.save
        format.html { redirect_to @jquery }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @jquery.update(jquery_params)
        format.html { redirect_to @jquery }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @jquery.destroy
    respond_to do |format|
      format.html { redirect_to jqueries_url }
    end
  end

  private
    def set_jquery
      @jquery = Jquery.find(params[:id])
    end

    def jquery_params
      params.fetch(:jquery, {})
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @pages = 'home'
  end

  def about
    @pages = 'about'
  end

  def contacts
    @pages = 'contacts'
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  def toastr_flash
    flash.each_with_object([]) do |(type, message), flash_messages|
      type = 'success' if type == 'notice'
      type = 'error' if type == 'alert'
      text = "<script>toastr.#{type}('#{message}', '', { closeButton: true, progressBar: true })</script>"
      flash_messages << text.html_safe if message
    end.join("\n").html_safe
  end

  def profile_picture account, width
    image_path = account.avatar.present? ? account.avatar.url : 'profile.jpg'
    image_tag(image_path, width: width, height: width, class: 'rounded')
  end

end

app/helpers/jqueries_helper.rb
module JqueriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/jqueries/_animation.html.erb
<!-- Navigation -->
<nav class="animation-nav">
  <div class='animation-container animation-div'>
    <object type='image/svg+xml' data='https://s3.amazonaws.com/codecademy-content/courses/jquery/audit/images/sole-logo.svg'></object>
    <div class="animation-div">
      <span class='animation-menu-button'>Menu</span>
      <span class='animation-login-button'>Login</span>
    </div>
  </div>
</nav>

<!-- Nav Menu -->
<div class='animation-nav-menu animation-hide animation-div'>
  <div class='animation-container animation-div'>
    <ul class="animation-ul">
      <li class="animation-li">Shoes</li>
      <li class="animation-li">Women's Shoes</li>
      <li class="animation-li">Men's Shoes</li>
      <li class="animation-li">Shoe Accessories</li>
      <li class="animation-li">Wholesale</li>
    </ul>
    <ul class="animation-ul">
      <li class="animation-li">Contact</li>
      <li class="animation-li">Twitter</li>
      <li class="animation-li">Facebook</li>
      <li class="animation-li">Instagram</li>
      <li class="animation-li">Email</li>
    </ul>
  </div>
</div>

<!-- Login Form -->
<div class='animation-login-form animation-div'>
  <div class='animation-container animation-div'>
    <form class="animation-form">
      <h4 class="animation-h4">Username</h4>
      <input class='animation-username' />
      <h4 class="animation-h4">Password</h4>
      <input type='password' />
      <input class='animation-sign-in-button' type='submit' value='Sign In' />
    </form>
  </div>
</div>

<!-- Product Cards -->
<div class='animation-container animation-div'>
  <div class='animation-product-card animation-div'>
    <div class='animation-product-photo animation-sole-air-ii animation-div'></div>
    <div class='animation-product-details animation-div'>
      <h4 class="animation-h4">Sole Air II</h4>
      <div class="animation-div">
        <p class="animation-p">$35</p>
        <div class='animation-more-details-button animation-div'>
          <img src='https://s3.amazonaws.com/codecademy-content/courses/jquery/audit/images/right-arrow.svg' />
        </div>
      </div>
    </div>

    <div class='animation-shoe-details animation-div'>
      <p class="animation-p">The ultimate in style and comfort, the Sole Air II's are great for walking and casual wearing.</p>
      <div class='animation-size-chart animation-div'>
        <h4 class="animation-h4">Size</h4>
        <ul class='animation-sizes'>
          <li class="animation-li">8</li>
          <li class="animation-li">9</li>
          <li class="animation-li">10</li>
          <li class="animation-li">11</li>
          <li class="animation-li">12</li>
        </ul>
      </div>
      <div class='animation-buy-now-button animation-disabled animation-div'>
        <h3 class="animation-h3">Add to cart</h3>
      </div>
    </div>
  </div>
</div>

<div class='animation-container animation-div'>
  <div class='animation-product-card animation-div'>
    <div class='animation-product-photo tidal-x animation-div'></div>
    <div class='animation-product-details animation-div'>
      <h4 class="animation-h4">Tidal X</h4>
      <div class="animation-div">
        <p class="animation-p">$40</p>
        <div class='animation-more-details-button animation-div'>
          <img class="animation-img" src='https://s3.amazonaws.com/codecademy-content/courses/jquery/audit/images/right-arrow.svg' />
        </div>
      </div>
    </div>

    <div class='animation-shoe-details animation-div'>
      <p class="animation-p">The Tidal X's signature rubber midsole make this the perfect running shoe. With a soft mesh upper, and synthetic polymer outsole, these shoes really fly.</p>
      <div class='animation-size-chart animation-div'>
        <h4 class="animation-h4">Size</h4>
        <ul class='animation-sizes'>
          <li class="animation-li">6</li>
          <li class="animation-li">7</li>
          <li class="animation-li">10</li>
          <li class="animation-li">12</li>
          <li class="animation-li">13</li>
        </ul>
      </div>
      <div class='animation-buy-now-button animation-disabled animation-div'>
        <h3 class="animation-h3">Add to cart</h3>
      </div>
    </div>

  </div>
</div>

<div class='animation-container animation-div'>
  <div class='animation-product-card animation-div'>
    <div class='animation-product-photo animation-dark-sole-original animation-div'></div>
    <div class='animation-product-details animation-div'>
      <h4 class="animation-h4">Dark Sole Original</h4>
      <div class="animation-div">
        <p class="animation-p">$60</p>
        <div class='animation-more-details-button animation-div'>
          <img class="animation-img" src='https://s3.amazonaws.com/codecademy-content/courses/jquery/audit/images/right-arrow.svg' />
        </div>
      </div>
    </div>

    <div class='animation-shoe-details animation-div'>
      <p class="animation-p">Light up the night with the Dark Sole Original. Lights around the midsole activate when stomped.</p>
      <div class='animation-size-chart animation-div'>
        <h4 class="animation-h4">Size</h4>
        <ul class='animation-sizes'>
          <li class="animation-li">9</li>
          <li class="animation-li">10</li>
          <li class="animation-li">10.5</li>
          <li class="animation-li">11</li>
        </ul>
      </div>
      <div class='animation-buy-now-button animation-disabled animation-div'>
        <h3 class="animation-h3">Add to cart</h3>
      </div>
    </div>
  </div>
</div>

<!-- Shopping cart -->
<div class='animation-shopping-cart animation-div'>
  <div class='animation-container animation-div'>
    <div class='animation-cart animation-div'>
      <object class="animation-object" type='image/svg+xml' data='https://s3.amazonaws.com/codecademy-content/courses/jquery/audit/images/shopping-cart.svg'></object>
      <h3 class='animation-items-qty animation-h3'>1</h3>
    </div>
    <h3 class="animation-h3">Checkout</h3>
  </div>
</div>

<footer class="animation-footer">
  <div class='animation-container animation-div'>
    <object class="animation-object" type='image/svg+xml' data='https://s3.amazonaws.com/codecademy-content/courses/jquery/audit/images/sole-logo.svg'></object>
    <div class="animation-div">Contact Us</div>
  </div>
</footer>

<script type="text/javascript">

  $(document).ready(() => {

    $('.animation-login-button').on('click', () => {
      $('.animation-login-form').toggle();
    });

    $('.animation-menu-button').on('mouseenter', () => {
      $('.animation-nav-menu').show();
      $('.animation-menu-button').addClass('animation-button-active');
      $('.animation-nav-menu').removeClass('animation-hide');

      $('.animation-menu-button').animate({
        fontSize: '24px'
      }, 200)
    })

    $('.animation-nav-menu').on('mouseleave', () => {
      $('.animation-menu-button').removeClass('animation-button-active')

      $('.animation-menu-button').animate({
        fontSize: '18px'
      }, 200)
    })

  });

</script>

app/views/jqueries/_change.html.erb
<div class="change-body">

  <div class = "change-outer-container">

    <header class="change-header">
      <h1 class="change-h1">TYP</h1>
      <h2 class="change-h2">Test-drive your text</h2>
    </header>

    <div class="change-formHolder">
      <form method="POST">
        <div class="change-third">
          Font Family <select name="change-font" id="change-font">
            <option value="helvetica" id="change-helvetica">Helvetica</option>
            <option value="times" id="change-times">Times</option>
            <option value="impact" id="change-impact">Impact</option>
            <option value="courier" id="change-courier">Courier</option>
            <option value="verdana" id="change-verdana">Verdana</option>
          </select>
        </div>

        <div class="change-third">
          Font Size
          <br>
          <input class="change-input" type="text" placeholder="12" id="change-size">
        </div>

        <div class="change-third">
          Font Weight  <select name="weight" id="change-weight">
           <option value="normal">Normal</option>
           <option value="bold">Bold</option>
           <option value="bolder">Bolder</option>
           <option value="lighter">lighter</option>
         </select>
        </div>
      </form>
    </div>

    <div class="change-preview">Sample Font</div>
    <textarea class="change-textarea" name="text" placeholder="Type something here and see what happens..." id="change-text" cols="30" rows="10"></textarea>
  </div>
</div>

<script type="text/javascript">

  $(document).ready(() => {

    $('#change-text').on('keyup', (event) => {
      $('.change-preview').html($(even.currentTarget).val());
    });

    $('#change-font').on('change', (event) => {
      $('.change-preview').css({
        fontFamily: $(event.currentTarget).val()
      })
    });

    $('#change-weight').on('change', (event) => {
      $('.change-preview').css({
        fontWeight: $(event.currentTarget).val()
      })
    });

    $('#change-SIZE').on('keyup', (event) => {
      let fontSize = $(event.currentTarget).val() + 'px';
      $('.change-preview').css({
        fontSize: fontSize
      })
    });

  })

</script>

app/views/jqueries/_closing.html.erb
<!-- Navigation -->
<nav class="closing-nav">
  <div class='closing-container closing-div'>
    <object type='image/svg+xml' data='https://s3.amazonaws.com/codecademy-content/courses/jquery/audit/images/sole-logo.svg'></object>
    <div class="closing-div">
      <span class='closing-menu-button'>Menu</span>
      <span class='closing-login-button'>Login</span>
    </div>
  </div>
</nav>

<!-- Nav Menu -->
<div class='closing-nav-menu closing-hide closing-div'>
  <div class='closing-container closing-div'>
    <ul class="closing-ul">
      <li class="closing-li">Shoes</li>
      <li class="closing-li">Women's Shoes</li>
      <li class="closing-li">Men's Shoes</li>
      <li class="closing-li">Shoe Accessories</li>
      <li class="closing-li">Wholesale</li>
    </ul>
    <ul class="closing-ul">
      <li class="closing-li">Contact</li>
      <li class="closing-li">Twitter</li>
      <li class="closing-li">Facebook</li>
      <li class="closing-li">Instagram</li>
      <li class="closing-li">Email</li>
    </ul>
  </div>
</div>

<!-- Login Form -->
<div class='closing-login-form closing-div'>
  <div class='closing-container closing-div'>
    <form class="closing-form">
      <h4 class="closing-h4">Username</h4>
      <input class='closing-input closing-username' />
      <h4 class="closing-h4">Password</h4>
      <input class="closing-input" type='password' />
      <input class='closing-input closing-sign-in-button' type='submit' value='Sign In' />
    </form>
  </div>
</div>

<!-- Product Cards -->
<div class='closing-container closing-div'>
  <div class='closing-product-card closing-div'>
    <div class='closing-product-photo sole-air-ii closing-div'></div>
    <div class='closing-product-details closing-div'>
      <h4 class="closing-h4">Sole Air II</h4>
      <div class="closing-div">
        <p class="closing-p">$35</p>
        <div class='closing-more-details-button closing-div'>
          <img class="closing-img" src='https://s3.amazonaws.com/codecademy-content/courses/jquery/audit/images/right-arrow.svg' />
        </div>
      </div>
    </div>

    <div class='closing-shoe-details closing-div'>
      <p class="closing-p">The ultimate in style and comfort, the Sole Air II's are great for walking and casual wearing.</p>
      <div class='closing-size-chart closing-div'>
        <h4 class="closing-h4">Size</h4>
        <ul class='closing-sizes'>
          <li class="closing-li">8</li>
          <li class="closing-li">9</li>
          <li class="closing-li">10</li>
          <li class="closing-li">11</li>
          <li class="closing-li">12</li>
        </ul>
      </div>
      <div class='closing-buy-now-button closing-disabled closing-div'>
        <h3>Add to cart</h3>
      </div>
    </div>
  </div>
</div>

<div class='closing-container closing-div'>
  <div class='closing-product-card closing-div'>
    <div class='closing-product-photo closing-tidal-x closing-div'></div>
    <div class='closing-product-details closing-div'>
      <h4 class="closing-h4">Tidal X</h4>
      <div class="closing-div">
        <p class="closing-p">$40</p>
        <div class='closing-more-details-button closing-div'>
          <img class="closing-img" src='https://s3.amazonaws.com/codecademy-content/courses/jquery/audit/images/right-arrow.svg' />
        </div>
      </div>
    </div>

    <div class='closing-shoe-details closing-div'>
      <p class="closing-p">The Tidal X's signature rubber midsole make this the perfect running shoe. With a soft mesh upper, and synthetic polymer outsole, these shoes really fly.</p>
      <div class='closing-size-chart closing-div'>
        <h4 class="closing-h4">Size</h4>
        <ul class='closing-sizes'>
          <li class="closing-li">6</li>
          <li class="closing-li">7</li>
          <li class="closing-li">10</li>
          <li class="closing-li">12</li>
          <li class="closing-li">13</li>
        </ul>
      </div>
      <div class='closing-buy-now-button closing-disabled closing-div'>
        <h3 class="closing-h3">Add to cart</h3>
      </div>
    </div>

  </div>
</div>

<div class='closing-container closing-div'>
  <div class='closing-product-card closing-div'>
    <div class='closing-product-photo closing-dark-sole-original closing-div'></div>
    <div class='closing-product-details closing-div'>
      <h4 class="closing-h4">Dark Sole Original</h4>
      <div class="closing-div">
        <p class="closing-p">$60</p>
        <div class='closing-more-details-button closing-div'>
          <img class="closing-img" src='https://s3.amazonaws.com/codecademy-content/courses/jquery/audit/images/right-arrow.svg' />
        </div>
      </div>
    </div>

    <div class='closing-shoe-details closing-div'>
      <p class="closing-p">Light up the night with the Dark Sole Original. Lights around the midsole activate when stomped.</p>
      <div class='closing-size-chart closing-div'>
        <h4 class="closing-h4">Size</h4>
        <ul class='closing-sizes'>
          <li class="closing-li">9</li>
          <li class="closing-li">10</li>
          <li class="closing-li">10.5</li>
          <li class="closing-li">11</li>
        </ul>
      </div>
      <div class='closing-buy-now-button closing-disabled closing-div'>
        <h3 class="closing-h3">Add to cart</h3>
      </div>
    </div>
  </div>
</div>

<!-- Shopping cart -->
<div class='closing-shopping-cart closing-div'>
  <div class='closing-container closing-div'>
    <div class='closing-cart closing-div'>
      <object class="closing-object" type='image/svg+xml' data='https://s3.amazonaws.com/codecademy-content/courses/jquery/audit/images/shopping-cart.svg'></object>
      <h3 class='closing-h3 closing-items-qty'>1</h3>
    </div>
    <h3 class="closing-h3">Checkout</h3>
  </div>
</div>

<footer class="closing-footer">
  <div class='closing-container closing-div'>
    <object class="closing-object" type='image/svg+xml' data='https://s3.amazonaws.com/codecademy-content/courses/jquery/audit/images/sole-logo.svg'></object>
    <div class="closing-div">Contact Us</div>
  </div>
</footer>

app/views/jqueries/_effects.html.erb
<table align='effects-center'>

  <tr class="effects-tr">
    <th class='effects-header-small effects-th'>
      <div class='effects-header-text'>Buttons</div>
    </th>
    <th class='effects-header-big effects-th'>
      <div class='effects-image-text'>Images</div>
    </th>
  </tr>

  <tr class="effects-tr">
    <th class='effects-button-col effects-th'>
      <button class="effects-hide-button effects-button">
        <div class = 'effects-button-text'>HIDE</div>
      </button>
    </th>
    <th rowspan = 3 class = 'effects-img-col effects-th'>
      <img src = "https://s3.amazonaws.com/codecademy-content/courses/jquery/effects/veggies.jpg" class ="effects-first-image">
    </th>
  </tr>

</table>

<script type="text/javascript">

  $(document).ready(() => {
    $('.effects-hide-button').on('click', () => {
      $('.effects-first-image').hide();
    })
  });

</script>

app/views/jqueries/_form.html.erb
<%= simple_form_for(@jquery) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/jqueries/_intro.html.erb
<div class="intro-header">
  <div class="intro-container">
    <div class="intro-row">
      <div class="intro-col-md-4">
        <h1 class="intro-h1">madison square market</h1>
      </div>
      <div class="intro-pull-right">

        <ul class="intro-ul">

          <li class="intro-dropdown intro-li" id="intro-cart">
            <h3 class="intro-h3">cart &#x25BE;</h3>
            <ul class="intro-dropdown-menu intro-ul" id="intro-cartMenu">
              <li class="intro-li">View Cart</li>
              <li class="intro-li">Saved Carts</li>
            </ul>
          </li>

          <li class="intro-dropdown intro-li"  id="intro-account">
            <h3 class="intro-h3">account &#x25BE;</h3>
            <ul class="intro-dropdown-menu intro-ul" id="intro-accountMenu">
              <li class="intro-li">View Account</li>
              <li class="intro-li">Check Order Status</li>
              <li class="intro-li">Sign in</li>
            </ul>
          </li>

          <li class="intro-dropdown intro-li"  id="intro-help">
            <h3 class="intro-h3">help &#x25BE;</h3>
            <ul class="intro-dropdown-menu intro-ul" id="intro-helpMenu">
              <li class="intro-li">FAQs</li>
              <li class="intro-li">Return Policy</li>
              <li class="intro-li">Shipping Info</li>
            </ul>
          </li>

        </ul>

      </div>
    </div>
  </div>
</div>

<div class="intro-main"></div>
<div class="intro-footer"></div>

<script type="text/javascript">

  $(document).ready(() => {

    $('.intro-hide-button').on('click', () => {
      $('.intro-first-image').hide();
    });

    $('.intro-show-button').on('click', () => {
      $('.intro-first-image').show();
    });

    $('.intro-toggle-button').on('click', () => {
      $('.intro-first-image').toggle();
    });

    $('.intro-fade-out-button').on('click', () => {
      $('.intro-fade-image').fadeOut(500);
    });

    $('.intro-fade-in-button').on('click', () => {
      $('.intro-fade-image').fadeIn(4000);
    });

    $('.intro-fade-toggle-button').on('click', () => {
      $('.intro-fade-image').fadeToggle();
    });

    $('.intro-up-button').on('click', () => {
      $('.intro-slide-image').slideUp(100);
    });

    $('.intro-down-button').on('click', () => {
      $('.intro-slide-image').slideDown('slow');
    });

    $('.intro-slide-toggle-button').on('click', () => {
      $('.intro-slide-image').slideToggle(400);
    });

  });

</script>

app/views/jqueries/_validation.html.erb
<div class = 'validation-card'>

  <div class = "validation-question">
    <div class = 'validation-question-text'>What is the capital of New York?</div>
  </div>

  <div class = 'validation-hint-box'>
    <div class = 'validation-hide-hint-text'>SHOW/HIDE HINT</div>
  </div>

  <div class = 'validation-hint'>
    <div class = 'validation-hide-hint-text'>The capital is not the largest city!</div>
  </div>

  <div class = 'validation-wrong-answer-one validation-answer'>
    <div class= 'validation-wrong-text-one validation-answer-text'>New York City</div>
  </div>

  <div class = 'validation-wrong-answer-two validation-answer'>
    <div class= 'validation-wrong-text-two validation-answer-text'>Buffalo</div>
  </div>

  <div class = 'validation-wrong-answer-three validation-answer'>
    <div class= 'validation-wrong-text-three validation-answer-text'>Syracuse</div>
  </div>

  <div class = 'validation-correct-answer validation-answer'>
    <div class = 'validation-correct-answer-text validation-answer-text'>Albany</div>
  </div>

  <div class = 'validation-result'>
    <div class = 'validation-smiley'> <img src='https://s3.amazonaws.com/codecademy-content/courses/jquery/effects/smile_icon.svg' /> </div>
    <div class = 'validation-frown'> <img src='https://s3.amazonaws.com/codecademy-content/courses/jquery/effects/frown_icon.svg' />  </div>
  </div>
</div>

<script type="text/javascript">

  $(document).ready(() =>{

    $('.validation-hint-box').on('click', () => {
      $('.validation-hint').slideToggle(400);
    })

    $('.validation-wrong-answer-one').on('click', () => {
      $('.validation-wrong-text-one').fadeOut('slow');
      $('.validation-wrong-text-one').show('validation-frown');
    })

    $('.validation-wrong-answer-two').on('click', () => {
      $('.validation-wrong-text-two').fadeOut('slow');
      $('.validation-wrong-text-two').show('validation-frown');
    })

    $('.validation-wrong-answer-three').on('click', () => {
      $('.validation-wrong-text-three').fadeOut('slow');
      $('.validation-wrong-text-three').show('validation-frown');
    })

    $('.validation-correct-answer').on('click', () => {
      $('validation-correct-text-answer').show('validation-smiley');
    })

  });

</script>

app/views/jqueries/edit.html.erb
<h1>Editing Jquery</h1>

<%= render 'form', jquery: @jquery %>

<%= link_to 'Show', @jquery %> |
<%= link_to 'Back', jqueries_path %>

app/views/jqueries/index.html.erb
<div class="container col-12">
  <div class="row">

    <div class="col-3">

    </div>

    <div class="col-7">

      <h1 class="mt-5 mb-5">Jqueries</h1>

      <div class="card shadow-lg border-0 mt-5">
        <%= render 'jqueries/menu' %>
      </div>

      <div class="card shadow-lg border-0 mt-5">
        <%= render 'jqueries/intro' %>
      </div>

      <div class="card shadow-lg border-0 mt-5">
        <%= render 'jqueries/effects' %>
      </div>

      <div class="card shadow-lg border-0 mt-5">
        <%= render 'jqueries/validation' %>
      </div>

      <div class="card shadow-lg border-0 mt-5">
        <%= render 'jqueries/events' %>
      </div>

      <div class="card shadow-lg border-0 mt-5">
        <%= render 'jqueries/target' %>
      </div>

      <div class="card shadow-lg border-0 mt-5">
        <%= render 'jqueries/animation' %>
      </div>

      <div class="card shadow-lg border-0 mt-5">
        <%= render 'jqueries/change' %>
      </div>

      <div class="card shadow-lg border-0 mt-5">
        <%= render 'jqueries/photo' %>
      </div>

      <div class="card shadow-lg border-0 mt-5">
        <%= render 'jqueries/closing' %>
      </div>

    </div>

    <div class="col-2">

    </div>
  </div>
</div>





<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jqueries.each do |jquery| %>
      <tr>
        <td><%= link_to 'Show', jquery %></td>
        <td><%= link_to 'Edit', edit_jquery_path(jquery) %></td>
        <td><%= link_to 'Destroy', jquery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Jquery', new_jquery_path %>

app/views/jqueries/show.html.erb
<%= link_to 'Edit', edit_jquery_path(@jquery) %> |
<%= link_to 'Back', jqueries_path %>

app/views/layouts/_nav.html.erb
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 bg-white border-bottom shadow-sm">
  <h5 class="my-0 mr-md-auto font-weight-normal"><%= link_to 'Jquery', root_path, class: 'text-dark text-decoration-none' %></h5>

  <nav class="my-2 my-md-0 mr-md-3">
    <%= link_to 'Home', root_path, class: "text-dark mr-3 text-decoration-none" %>
    <%= link_to 'About', about_path, class: "text-dark mr-3 text-decoration-none" %>
    <%= link_to 'Contacts', contacts_path, class: "text-dark mr-3 text-decoration-none" %>
    <%= link_to 'Jquery', jqueries_path, class: "text-dark mr-3 text-decoration-none" %>
  </nav>

  <% if account_signed_in? %>

    <nav class="my-2 my-md-0 mr-md-3">
      <%= link_to 'Settings', edit_account_registration_path, class: "text-dark mr-3 text-decoration-none" %>
    </nav>

    <%= link_to profile_path(current_account) do %>
      <span class="badge badge-secondary float-right mr-1">
        <%= current_account.username %>
      </span>
    <% end %>

    <span class="float-right mr-3 ml-3"><%= link_to profile_picture(current_account, 40), edit_account_registration_path(current_account) %></span>

    <%= link_to 'Sign out', destroy_account_session_path, method: :delete, class: "btn btn-outline-danger" %>
  <% else %>
    <%= link_to 'Sign in', new_account_session_path, class: "btn btn-success mr-3" %>
    <%= link_to 'Sign up', new_account_registration_path, class: "btn btn-secondary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jquery</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% cache do %>
      <div class="<%= @page %>-page">
        <%= render 'layouts/nav' %>

        <%= toastr_flash %>

        <%= yield %>
      </div>
    <% end %>

  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>